steps:
  - name: "gradle:7.1-jdk8"
    entrypoint: "gradle"
    args: ["--stacktrace", "build"]
artifacts:
  objects:
    location: "gs://$_ARTIFACT_BUCKET/$PROJECT_ID/$BUILD_ID"
    paths: ["build/distributions/*.zip"]
