steps:
  - name: "gradle:7.1-jdk8"
    entrypoint: "gradle"
    args: ["--stacktrace", "-Pprefab.release", "release"]
artifacts:
  objects:
    location: "gs://$_ARTIFACT_BUCKET/$PROJECT_ID/$TAG_NAME"
    paths: ["build/distributions/*.zip"]
